version: "3"

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hr_bot

  api:
    build:
      context: ./api
    env_file:
      - ./.env
    ports:
      - "8010:8010"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - hr_bot

  bot:
    build:
      context: ./bot
    env_file:
      - ./.env
    depends_on:
      - api
    networks:
      - hr_bot

networks:
  hr_bot: